version: "3"
services:
  xbworld:
    build:
      context: .
      dockerfile: Dockerfile.railway
    container_name: xbworld
    ports:
      - "8080:8080"
      - "6000-6009:6000-6009"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - data:/app/data/savegames

volumes:
  data:
